### ISSUE TITLE
Export objects table to sherlock instances for long lightcurve feature checks

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-lsst#22]
We had a quick discussion at QUB this morning relating to the ongoing issue of jdmin (and other attributes) that rely only on the contents of the lightcurve contents of the packet.  While asking LSST to add more features at source helps, this exposes us to constantly requesting more from LSST as we build more features. The problem has been highlighted several times in ZTF as users search for more long-lived slowly varying objects (e.g. extremely long lightcurve transients).

Dave pointed out that, as part of the ingestion process, the filter nodes must do a Sherlock call. Sherlock is currently a (very large) read-only database. How much work would it be for us to export the relatively small objects table to Sherlock periodically (e.g. once per day)? Then we enhance the Sherlock Wrapper to query the contents of the long-lived features for that object as the object arrives.

This approach has two advantages:
1. We preserve the state of long lived features. In the case where there is a query problem we fall back to querying the features based on the packet lightcurve.
2. It reduces the strain on Sherlock. We don't need to query Sherlock for context information that we already know from previous Sherlock calls for that object. (Hence we do the object check first, then query Sherlock if there is no context info.)

**Comment by RoyWilliams** [comment]
Are you suggesting this for ZTF that will last another 4 months? 
Or for LSST that already has a 12-month lightcurve and will include minTai?
Is the suggestion to throw out the 12-month lightcurve and compute all features from the long lightcurve?
As I recall, the architecture already incudes a Sherlock cache that somehow has not been implemented.

**Comment by genghisken** [comment]
1. Up for discussion. Depends on how much work this involves. Agreed that by the time it's implemented it might not be relevant to a dead ZTF survey, hence the issue was raised in this repo for discussion, not lasair4.
2. Great that LSST has a agreed to give us minTai. What if we want mingFlux, minrFlux, etc? Do we have to keep going back to them with suggestions that it might be good to add this and that attribute? There's a lot of interest in extreme slow varying transients, so not sure that even 12 months is long enough either. (Best to talk to the actual users about this one.)
3. Good question. This could get messy. I guess some features (e.g. min something) are easy to compute and cache, others not so easy (e.g. jdmin gets updated only if the value is lower than the one in the cached object table). At the moment I don't think we run any of these computations on the main database - only on the filters - and I don't believe the filter nodes talk to cassandra - hence they don't have access to the full lightcurve. (Correct me if I'm wrong!)
4. The Sherlock cache never got implemented. So there's potential for speeding existing things up here.

**Comment by RoyWilliams** [comment]
Below are architectures (1) and (2) and how to measure performance. 

1.  Short light curves (original architecture): Ingestion rate is limited by number of filter nodes.
- Required metric: alerts per second thru a single filter node with no active filters.

2. Long light curves (proposed architecture): Ingestion rate is limited by cassandra read/write speed. Remember the writing will in general be simultaneous to the read.
- Required metrics: alerts per second for 
    - pure Cassandra write 
    - pure Cassandraread 
    - simultaneous Cassandra write and read

**Comment by RoyWilliams** [comment]
Why are people doing archival studies of ZTF using Lasair? Why not use the data releases? (Answer: the [IPAC interface](https://irsa.ipac.caltech.edu/docs/program_interface/ztf_api.html) is not nearly as good as Lasair). Perhaps with LSST these archival searches will be done on the system designed for that -- i.e. the RSP attached to the data release?

**Comment by smarttgit** [comment]
I understand the science problem (but not the technical problem) and we should find a way to allow users to extract back to before 100 days. I wouldn't define that as archival study science. It's still using the difference imaging and alert information, just longer than 100 days.

I don't fully understand what the technical problem in allowing access to the full lightcurves, as they will be in Cassandra - can discuss further.

**Comment by RoyWilliams** [comment]
We are building a car that can do 200mph, but we have not been able to run at full speed. Our first prototype has been doing 50mph, and we are in the midst of making a new model to run at full speed. But suddenly there is a new requirement to carry a sofa on the roof of the old and/or the new car -- while racing at full speed. Stop all work! Back to the drawing board!

Lasair is designed so the databases are downstream of feature building and alert filtering. This is so filtering can be done in a parallel scalable way, meaning that speed can be ramped up by simply adding more filter nodes. Writing lightcurves to Cassandra is fast because nobody is trying to read at the same time. Tying feature-building to the database destroys this scalability. In the current design, speed can be increased simply by adding more filter nodes; but we will lose that scalability if every filter node is trying to interact with Cassandra.

[Here is a nice article about Cassandra performance when reading](https://www.zymr.com/blog/cassandra-good-read-operations). "Eventual consistency semantics" works well for the current Lasair architecture (fast writing) but not if the filter nodes are reading the same stuff back again as fast as they can.

I suggest that we first demonstrate the original Lasair design operating at full LSST speeds, along with with hundreds of active queries and watchlists. This is what we have promised to deliver, and I for one am nervous about it. If somehow that turns out to be easy, we might think about adding the Frohmeier-Nichol Requirement.

**Comment by smarttgit** [comment]
I'm still not convinced that reading from Cassandra will seriously affect the speed of the alert filtering. The queries will be few and not frequent since the timescales are long, and the number of objects will be small. We certainly shouldn't write this off as not possible.

**Comment by RoyWilliams** [comment]
Isn't the suggestion to compute features from the full lightcurve? 
EVERY ALERT generates a request to Cassandra.

**Comment by smarttgit** [comment]
No we're absolutely not doing that, >99% will be variable stars and you are completely right, that is best done on the RSP. 

But for long lived transients, maybe a few 100 per yer, that is when we're trigger a request to Cassandra. All we need is a reason to trigger. 

E.g. the features we compute on the alert packet data suggest a >12 month duration of a transient. That's when we would trigger.

**Comment by genghisken** [comment]
Thanks for the comments.  I'm not trying to sabotage the current design, just open a conversation about some drawbacks of our current setup that's been a repeated theme from our power users.

I guess when I opened this ticket, I was thinking about "simple" features, like we currently store - e.g. min, max of something. Those are done on the full lightcurve periodically (how this is done, and how often, I haven't yet thought through - since we need the whole LC). These features are fed forward / replicated (e.g. once a day - another thing I haven't yet thought through) to the objects copy on Sherlock.

The feature code runs normally on the incoming lightcurve from the alert packet. These are cross-checked (as part of the sherlock wrapper) against the simple features in the object copy on Sherlock. Features get written as normal, with the simple features overriding the ones calculated from the incoming LC.

As for Cassandra reads - yes - I've pointed out this before - it's definitely better at writing than reading. (I can read up on read quorum configuration - it's probably tuneable.) But I don't think this necessarily rules it out for use in the filter process. I think I managed to get 1000 lightcurves a second out of the setup at QUB, and we'd only grab information for objects not classified as VS/BS.

**Comment by smarttgit** [comment]
Yes, vast majority of diaObjects (>~99% at a reasonable guess) that are transient in nature will have all information required within the 12 months of history. 

Vast majority  of long lived diaObjects generally (>99%, also a reasonable guess) will be stars, or potentially low level AGN variability. 

What we talking about here is a small number that are not stars or AGN, but transients (which we can flag) and last longer than 12 months. Will be few reads, at most in the 10-100s  per day rather than the 1000s per sec.

**Comment by RoyWilliams** [comment]
Question 1: How to decide, based only on the alert plus Sherlock, on which objects get the special treatment.
Question 2: How to inform users that some object features are computed on long, rather than short, lightcurve.
Question 3: Graham Smith says he hopes for a custom, additional, LSST pipeline to run, generating special alerts. How do we distinguish these from normal alerts?

**Comment by gpfrancis** [comment]
From the above it sounds to me like there are three separate use cases:
1. Stephen's long-lived transients: adding additional information to a small (<<1%) number of alerts that can be selected based on what we already have in the alert packet + Sherlock.
2. Ken's new features: adding additional "simple" features to every alert, computed from the full lightcurve.
3. Graham's custom pipeline: I have no idea what this is about.

My take:
1. Looks to me like a well defined use case that is a perfect fit for an annotator; we just go ahead and build one for it. This has the great advantage that we can prototype it on the ZTF system *without* messing with the Lasair 4 codebase again, then port it over to LSST when it's ready. This also naturally answers Roy's questions above.
2. Looks to me like it should be *possible* using Cassandra (not the object DB). But it's potentially a fairly big addition to the system and the requirements are currently pretty vague.
3. Is news to me.

**Comment by genghisken** [comment]
A general discussion about this concluded that we just need to educate our users & guide them towards use of the API.
* First that they understand that the "min" values of attributes refer to information in the packet only. (None of the users seem to understand this.)
* Second, since they already have code written that listens to the Kafka stream, it should be straightforward, after an object has triggered, to use the API to recalculate the values from the whole lightcurve information.
